---
title: "nettoyage donnees"
author: "Marie Joigneau"
date: '2022-09-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dataset
```{r}
library(data.table)

# We open the table and convert it in data.table :
stars <- fread("data/stars.csv",sep=",")
stars <- data.table(stars)
stars
```

```{r}
# We rename correctly the columns :
names(stars)
names(stars)[1] <- "Temperature.K"
names(stars)[2] <- "Luminosity.L.Lo"
names(stars)[3] <- "Radius.R.Ro"
names(stars)[4] <- "Absolute_Magnitude.Mv"
names(stars)[5] <- "Star_Type"
names(stars)[6] <- "Star_Color"
names(stars)[7] <- "Spectral_Class"
names(stars)
```

# File errors

```{r}
# We convert in factor :
stars$Star_Type <- as.factor(stars$Star_Type)
stars$Star_Color <- as.factor(stars$Star_Color)
stars$Spectral_Class <- as.factor(stars$Spectral_Class)

# Then we check the levels :
levels(stars$Star_Type)
levels(stars$Star_Color)
levels(stars$Spectral_Class)
```

```{r}
# To modify a level, I need to convert it into character :
stars$Star_Color <- as.character(stars$Star_Color)
stars$Star_Type <- as.character(stars$Star_Type)

# So :
stars[Star_Color=="Blue-White" | Star_Color=="Blue white" | Star_Color=="Blue White"]$Star_Color <- "Blue-white"
stars[Star_Color=="white" | Star_Color=="Whitish"]$Star_Color <- "White"
stars[Star_Color=="White-Yellow" | Star_Color=="yellow-white"]$Star_Color <- "White-yellow"
stars[Star_Color=="yellowish"]$Star_Color <- "Yellowish"
stars[Star_Color=="Pale yellow orange"]$Star_Color <- "Pale-yellow-orange"
stars[Star_Color=="Yellowish White"]$Star_Color <- "White-yellow"

# And :
stars[Star_Type=="0"]$Star_Type <- "Brown_Dwarf"
stars[Star_Type=="1"]$Star_Type <- "Red_Dwarf"
stars[Star_Type=="2"]$Star_Type <- "White_Dwarf"
stars[Star_Type=="3"]$Star_Type <- "Main_Sequence"
stars[Star_Type=="4"]$Star_Type <- "Supergiant"
stars[Star_Type=="5"]$Star_Type <- "Hypergiant"

# Then to put it back into factor and check again the levels :
stars$Star_Color <- as.factor(stars$Star_Color)
stars$Star_Type <- as.factor(stars$Star_Type)
levels(stars$Star_Color)
levels(stars$Star_Type)
```

# New dataset

```{r}
write.csv(stars,"data/stars_by_Marie.csv", row.names = FALSE)
```

Enjoy :)
